name: CI – Android Debug Build

on:
  push:
    branches:
      - master
      - 'release/*'
  pull_request:
    branches:
      - master
      - 'release/*'

jobs:
  build-android-debug:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: ${{ runner.tool_cache }}/android-sdk
      JAVA_HOME: ${{ runner.tool_cache }}/java

    steps:
    - name: Check out repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm' # or 'npm'

    - name: Install dependencies
      run: |
        npm install --frozen-lockfile
        # or: npm ci

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 33
        build-tools: 33.0.2

    - name: Accept Android licenses
      run: yes | sdkmanager --licenses

    - name: Build Android (Debug)
      working-directory: android
      run: |
        ./gradlew assembleDebug

    - name: Archive Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
